#! /bin/sh
echo "Please enter filename:"
read filename
echo "Please enter resolution: 1280x800 800x600 etc."
read resolution
ffmpeg -f alsa -ac 2 -i hw:0,0 -f x11grab -s $resolution -r 24 -i :0.0 -qscale 5 $filename.mp4


